export const ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
};

export const ERROR_NAMES = {
  USER_NOT_FOUND: 'UserNotFoundError',
  EMAIL_ALREADY_IN_USE: 'EmailAlreadyInUse',
};

export const ERROR_STATUS_CODES = {
  // Client Errors (4xx)
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,

  // Server Errors (5xx)
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

export const TESTING_DATABASE_PARAMS = {
  DATABASE_URL: 'file:dev.db?mode=memory&cache=shared',
};
